minimumReleaseAge: 2880
minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - "@jaykingson/vite-plus-base"

packages:
  - packages/*
catalogMode: prefer
catalog:
  "@types/node": ^24
  bingo: ^0.9.3
  typescript: ^7.0.2
  zod: ^4.0.0
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
  bingo-stratum: 0.7.1
overrides:
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
