name: Release
on:
  push:
    branches:
      - main
concurrency:
  group: "${{ github.workflow }}"
jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
      - run: vp install --frozen-lockfile
      - run: vp check
      - run: vp run -r test
      - run: vp run -r build
      - run: "vp run -r lint:package"
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v2
        with:
          version-script: vp run version-packages
          publish-script: vp run release
          commit-message: Version Packages
          pr-title: Version Packages
          create-github-releases: true
